from __future__ import annotations

import re

from .models import BusinessProfile, CampaignInput, EmailDraft, LeadInput, LeadScore
from .compliance import ComplianceAgent
from .llm import LLMRouter


class EmailPersonalizationAgent:
    def __init__(
        self,
        compliance: ComplianceAgent | None = None,
        llm_router: LLMRouter | None = None,
        unsubscribe_base_url: str = "",
        unsubscribe_secret: str = "",
    ) -> None:
        self.compliance = compliance or ComplianceAgent()
        self.llm_router = llm_router
        self.unsubscribe_base_url = unsubscribe_base_url
        self.unsubscribe_secret = unsubscribe_secret

    def draft(self, profile: BusinessProfile, campaign: CampaignInput, lead: LeadInput, score: LeadScore) -> EmailDraft:
        warnings: list[str] = []
        llm_draft, llm_error = self.llm_router.draft_email(profile, campaign, lead) if self.llm_router else (None, "")
        if llm_draft and llm_draft.get("subject") and llm_draft.get("body"):
            subject = llm_draft["subject"]
            body = llm_draft["body"]
            reason = llm_draft.get("personalization_reason", "Generated by LLM.")
            generated_by = "llm"
        else:
            # A "successful" LLM call whose subject/body stripped to empty is still
            # a failure — record it so the fallback stays visible.
            if llm_draft is not None and not llm_error:
                llm_error = "llm_returned_blank_fields"
            value_prop = profile.value_propositions[0] if profile.value_propositions else "reliable supply and responsive service"
            lead_context = lead.context or f"the {lead.industry or 'your'} sector"
            variables = {
                "first_name": lead.first_name or "there",
                "last_name": lead.last_name,
                "company_name": lead.company_name,
                "lead_context": lead_context,
                "value_prop": value_prop,
                "sender_name": campaign.sender_name,
                "sender_email": campaign.sender_email,
                "target_region": campaign.target_region,
            }
            body, unknown_vars = self._render(campaign.template, variables)
            warnings.extend(f"unknown_variable:{name}" for name in unknown_vars)
            subject = f"Potential supply fit for {lead.company_name}"
            reason = f"Personalized using title '{lead.title}', company '{lead.company_name}', and context '{lead_context}'."
            generated_by = "fallback"
        unsubscribe_link = ""
        if self.unsubscribe_base_url and self.unsubscribe_secret and lead.email:
            from .unsubscribe import unsubscribe_url

            unsubscribe_link = unsubscribe_url(self.unsubscribe_base_url, lead.email, self.unsubscribe_secret)
        sender_identity = ""
        if profile.postal_address:
            sender_identity = f"{campaign.sender_name} · {profile.company_name} · {profile.postal_address}"
        body = self.compliance.add_opt_out_footer(body, unsubscribe_url=unsubscribe_link, sender_identity=sender_identity)
        compliance = self.compliance.check_draft(lead, campaign, body)
        return EmailDraft(
            lead=lead,
            subject=subject,
            body=body,
            personalization_reason=reason,
            lead_score=score,
            compliance=compliance,
            approval_required=True,
            generated_by=generated_by,
            llm_error=llm_error,
            render_warnings=warnings,
        )

    def _render(self, template: str, variables: dict[str, str]) -> tuple[str, list[str]]:
        unknown: set[str] = set()

        def replace(match: re.Match[str]) -> str:
            key = match.group(1).strip()
            if key not in variables:
                unknown.add(key)
                return ""
            return variables[key]

        rendered = re.sub(r"{{\s*([^}]+)\s*}}", replace, template)
        return rendered, sorted(unknown)
